### ISSUE TITLE
ComfyUI Workflow for use of OMS

### ISSUE THREAD

**Issue by Piscabo** [longgui0318/comfyui-magic-clothing#1]
Any example Workflow, and what models need to be placed in which folders?
Some small write-up would be nice. 
Thanks.

**Comment by longgui0318** [comment]
Still in development, @ you when it's done

**Comment by Piscabo** [comment]
> Still in development, @ you when it's done

Any news on the use of this?

**Comment by longgui0318** [comment]
I'm still making revisions and have encountered some unexpected bugs, but I'm nearing the end.

**Comment by longgui0318** [comment]
@Piscabo Preview released

**Comment by Piscabo** [comment]
> @Piscabo Preview released

I see it's no longer OMS?

So where does this model fit into this OMS?
https://huggingface.co/kaeru-shigure/oms_b_openclip_xl/tree/main/oms_module

Also getting this error.
![image](https://github.com/longgui0318/comfyui-magic-clothing/assets/123719842/cd63c19d-57b7-434e-a096-2bbc7657baf8)

**Comment by longgui0318** [comment]
> I see it's no longer OMS?

The OMS we mentioned is not the same repository that I develop for https://github.com/ShineChen1024/MagicClothing. This repository used to be called OMS.

I'll take a look at the one you posted later today, and if it's easy to implement I'll open another repository to implement it.




> Also getting this error.

The unet must be MagicClothing. Also the model is based on sd1.5

**Comment by longgui0318** [comment]
@Piscabo I looked at the code and it's not complicated, I'll release it in a week or so

https://github.com/longgui0318/comfyui-one-more-step
