### ISSUE TITLE
Attention issue

### ISSUE THREAD

**Issue by alexgenovese** [longgui0318/comfyui-magic-clothing#3]
Hi, 

I got this issue on mac: 

```
/custom_nodes/comfyui-oms-diffusion/oms_diffusion_nodes.py", line 149, in get_area_and_mult
    conditioning["c_attn_stored_area"] = AttnStoredExtra(torch.tensor([area[0],area[1],area[2],area[3]]))
                                                                       ~~~~^^^
TypeError: 'NoneType' object is not subscriptable
``` 

thank you

**Comment by longgui0318** [comment]
Can you share your workflow and test images. Can you remove some of the irrelevant content so that I can test it

**Comment by longgui0318** [comment]
I found the problem, comfyui updated the implementation, I need to follow up on it and will reply when it's resolved. For related updates read [here](https://github.com/comfyanonymous/ComfyUI/commit/a5e6a632f9f16e5b3c72c428820bce67b05446bf)

**Comment by longgui0318** [comment]
I tried to fix it, if anything else goes wrong, please reply to this issue

**Comment by alexgenovese** [comment]
![Screenshot 2024-06-14 alle 17 19 47](https://github.com/longgui0318/comfyui-magic-clothing/assets/423745/46f4bb7c-58a5-44c3-915b-831f4f960529)

I don't know if it's linked to this issue: 

`Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.62it/s]
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
`

**Comment by longgui0318** [comment]
This node is part of the ComfyUI_MagicClothing project, please verify it and then take another look.
