### ISSUE TITLE
Wierd results 

### ISSUE THREAD

**Issue by schananas** [longgui0318/comfyui-magic-clothing#8]
Hi, can you help me understand why im I getting wierd result?
I have only changed segmentation part, everything else is unchanged.

![image](https://github.com/longgui0318/comfyui-magic-clothing/assets/1223547/740ce55c-6d2e-44f5-9c38-ed44a86cd48a)
[wierd_result_magic.json](https://github.com/user-attachments/files/16109307/wierd_result_magic.json)

**Comment by longgui0318** [comment]
![image](https://github.com/longgui0318/comfyui-magic-clothing/assets/3406303/fd87f7a4-4183-4aed-a7e3-32b85caae8f5)
Please note that the focus should be on conveying the clothing information, not the mask, as he does not yet have the clothing information. In my example, processing the mask is merely to extract the clothing information more precisely.

注意，需要将衣服信息传递过去，而不是遮罩，因为衣服信息他还没有，我的例子中处理遮罩只是为了更精确的提取衣服信息
