### ISSUE TITLE
How can I apply this with Image 2 Image? (Img2img)

### ISSUE THREAD

**Issue by ClothingAI** [longgui0318/comfyui-magic-clothing#9]
Hi,
The problem with image 2 image is that in order for it to work, it needs to have a KSampler that receives the same width and height for both:
- The latent image from the (input image)
- "feature image" entering the node "Add Magic Clothing Attention"

The problem when having images of the same dimensions is that the image for the clothing will take the full image, and the input image (for img2img) has lot going on: "a person, legs, hands etc)

So when you try to pass all that through the sampler, it will "merge" the cloth (t shirt for instance) into the full body of the input image, and it does not work well.
Also, another problem with img2img:
- if you do a high denoise, you can get better clothing reproduction, but you lose the original subject
- if you have low denoise, you keep the subject, but the clothing is not copied well.

Any solutions please?

**Comment by longgui0318** [comment]
There is no real solution, you can refer to other solutions in the community. The effect of the magic clothing is hard to cope with for production use.

**Comment by ClothingAI** [comment]
@longgui0318  Where can I find other workflows from the community? Where is the community located on? Do you know other places where people share and talk about this? Thanks

**Comment by longgui0318** [comment]
1. [MaX4Zero](https://github.com/NadavOrzech/MaX4Zero)
2. [CatVTON](https://github.com/Zheng-Chong/CatVTON)

Recently, it seems that there are many similar developments. It might be worth keeping an eye on the papers, but I've been busy with other matters lately and haven't paid much attention to virtual dressing.

**Comment by ClothingAI** [comment]
Hi @longgui0318  any news since?
You shared Max4zero, which has not comfyui node yet I believe right? Unless I missed it.
So to use it, I simply need to git clone the repo, and isntall it then run the script?
I see they mention "diffusers", what is that? I am not sure how that works, will I have to configure extra things to make it work?

I usually clone repos, install them with the reqs.txt, then run the script
But I don't know anything about "diffusers"? What extra things are needed so I can run that repository (Max4zero) in term of diffusers? I am not sure I understand

**Comment by longgui0318** [comment]
You can use the diffusers warp method for quick integration. However, if you need to reuse the ipadapter or contentNet from comfyui, you will still need to implement it native. You can take a look at the code from this project, which can serve as your template code.

**Comment by longgui0318** [comment]
Additionally, sharing these two examples does not necessarily mean they are superior to Magic-Clothing; it merely illustrates that the community has a wider range of models to choose from.

**Comment by ClothingAI** [comment]
> Additionally, sharing these two examples does not necessarily mean they are superior to Magic-Clothing; it merely illustrates that the community has a wider range of models to choose from.

I understand, I even stumbled upon ComfyUi_Seg_VITON, which looks promising, but the issues seem to suggest it is abandonend, and some problem with "missing" checkpoint? I am not sure.

Anyway, back to the diffusers, I am not sure at all what it is, I have always used local installations, does "diffusers" mean you connect you py code to some API that uses some AI model in the cloud? Sorry if my question sound stupid.
(Same I don't know what is warp method, I guess I could google it but I do really know nothing about diffusers to begin with), I think it is perhaps related to huggingface? That's where I saw that word thrown around, but I am not sure. (When I go check for files in their website)

As for magic clothing, I see there are 2 repos right? yours, which states "not the diffuers version" in the description, and the other one.
I tried the other one, right now, becuase it had so many workflow examples, did you check them?  Look they have like 7 examples (even described in the readme) https://github.com/frankchieng/ComfyUI_MagicClothing

I was not able to use them because of some errors, I wonder if its related to diffusers, the node they are using have this "PIPE" field:
![image](https://github.com/user-attachments/assets/48ca0a48-ca9f-424b-ad1d-8eabdc873a2d)

Is this related to diffusers? I mean I dont see these models locally yet the node wants to use them.

My request or my WISH, is to have the same workflows/json that other repo has, inside YOURS.
One of their workflows, seems to be doing what I wanted to do

**Comment by longgui0318** [comment]
The version you shared is actually based on diffusers. My repository doesn't have many examples because I'm quite lazy myself, but I will add the examples you mentioned in the near future.
Additionally, AI systems like kimi and chatgpt can provide excellent explanations of what diffusers are. For areas where one is not proficient, AI can offer more assistance.

**Comment by ClothingAI** [comment]
Ok thanks, I will try to copy their workflow into yours (seems yours is local and not based in diffusers (I will go ask chatgpt about it, but I am pretty sure this king of thing can be undertood only with practice not just theory)

**Comment by ClothingAI** [comment]
For reference, this is what copilot says, this is what I suspected (unless the AI has hallucinated?)

> The diffusers library often uses a concept called “pipelines” (sometimes abbreviated as “PIPE”) to manage and execute the diffusion process. These pipelines are essentially pre-configured models that can be called upon via an API to generate data.
> 
> Diffusers and Pipelines:
> Pipelines: In the diffusers library, a pipeline is a high-level interface that encapsulates the entire process of generating data. It includes all the necessary steps, from adding noise to refining the output.
> API Calls: These pipelines can be easily called through an API, making it convenient to integrate into various applications. This modular approach allows for flexibility and ease of use.
> ComfyUI Version:
> Alternative Models: The ComfyUI-supported version might use different models or frameworks that don’t rely on the diffusers library. These could be other types of generative models like GANs or VAEs, which have their own methods and interfaces for generating data.
> Integration: The focus here is on seamless integration with ComfyUI and modules like ipadapter, which might offer specific advantages or features not available in the diffusers version.
> In summary, the diffusers version uses pipelines for a streamlined and modular approach to data generation, while the ComfyUI version might leverage different models for better integration and specific functionalities.

**Comment by ClothingAI** [comment]
OK I got into a rabbit hole reading about this, and I found this example about Stable DIffusion:
https://huggingface.co/docs/diffusers/v0.30.2/en/api/pipelines/stable_diffusion/text2img#diffusers.StableDiffusionPipeline
Have you heard about runwayML removing their mode from huggingFace? That's unprecendented
